# Generated by Django 5.2.8 on 2025-12-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="photos/products/"),
        ),
    ]
