"""
Django settings for furniture_store project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import importlib
import os

_dj_database_url_spec = importlib.util.find_spec("dj_database_url")
if _dj_database_url_spec:
    dj_database_url = importlib.import_module("dj_database_url")
else:  # pragma: no cover - executed only when dj-database-url is absent
    class _DjDatabaseUrlFallback:
        def config(self, *_, **__):
            raise ImportError(
                "dj-database-url is required when DATABASE_URL is set. "
                "Install it with `pip install dj-database-url`."
            )

    dj_database_url = _DjDatabaseUrlFallback()

_decouple_spec = importlib.util.find_spec("decouple")
if _decouple_spec:
    decouple = importlib.import_module("decouple")
    config = decouple.config
    Csv = decouple.Csv
else:  # pragma: no cover - executed only when python-decouple is absent
    def _to_bool(value):
        """Minimal bool caster similar to python-decouple."""
        if isinstance(value, bool):
            return value
        normalized = str(value).strip().lower()
        if normalized in {"1", "true", "t", "yes", "y", "on"}:
            return True
        if normalized in {"0", "false", "f", "no", "n", "off"}:
            return False
        raise ValueError(f"Invalid boolean value: {value}")

    def _apply_cast(value, cast):
        if cast in (None, str) or value is None:
            return value
        if cast is bool:
            return _to_bool(value)
        if isinstance(cast, type):
            return value if isinstance(value, cast) else cast(value)
        if callable(cast):
            return cast(value)
        return value

    class Csv:
        def __init__(self, delimiter=",", strip=True, ignore_empty=True):
            self.delimiter = delimiter
            self.strip = strip
            self.ignore_empty = ignore_empty

        def __call__(self, value):
            if value is None:
                return []
            if isinstance(value, (list, tuple)):
                return list(value)
            items = str(value).split(self.delimiter)
            if self.strip:
                items = [item.strip() for item in items]
            if self.ignore_empty:
                items = [item for item in items if item]
            return items

    def config(option, default=None, cast=str):
        raw = os.getenv(option)
        if raw is None:
            return _apply_cast(default, cast)
        return _apply_cast(raw, cast)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default="django-insecure-s*ju%pwu6c^n3nyza-4(w@qx_$$y_u5#=qpmt=-9049a^_8w95")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS configuration
_allowed_hosts = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
# Ensure localhost and 127.0.0.1 are always included for local development
if DEBUG:
    if not _allowed_hosts:
        ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    else:
        # Merge with defaults to ensure localhost and 127.0.0.1 are present
        ALLOWED_HOSTS = list(set(_allowed_hosts + ['localhost', '127.0.0.1']))
else:
    ALLOWED_HOSTS = _allowed_hosts if _allowed_hosts else []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "crispy_forms",
    "crispy_bootstrap5",
    "storages",
    "accounts",
    "store",
    "cart",
    "orders",
    "payments",
    "reviews",
    "marketing",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Add WhiteNoise middleware only in production (Heroku)
if not DEBUG:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "furniture_store.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.cart_context",
                "core.context_processors.site_context",
            ],
        },
    },
]

WSGI_APPLICATION = "furniture_store.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = config("DATABASE_URL", default="")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Only attempt Postgres when explicit credentials are supplied; otherwise
    # fall back to SQLite for a frictionless local setup.
    DB_NAME = config("DB_NAME", default="")
    DB_USER = config("DB_USER", default="")
    DB_PASSWORD = config("DB_PASSWORD", default="")
    DB_HOST = config("DB_HOST", default="localhost")
    DB_PORT = config("DB_PORT", default="5432")

    if DB_NAME and DB_USER:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": DB_NAME,
                "USER": DB_USER,
                "PASSWORD": DB_PASSWORD,
                "HOST": DB_HOST,
                "PORT": DB_PORT,
            }
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for Heroku (production only)
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

USE_AWS = config("USE_AWS", default=False, cast=bool)

if USE_AWS:
    # AWS S3 Configuration for Production - Media files only
    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
    raw_location = config("AWS_LOCATION", default="media")
    AWS_LOCATION = (raw_location.strip().strip("/") or "media") if raw_location else "media"
    # Extract region code (e.g., 'eu-west-1' from 'Europe (Ireland) eu-west-1')
    region_config = config("AWS_S3_REGION_NAME", default="")
    AWS_S3_REGION_NAME = region_config.split()[-1] if region_config else ""
    if AWS_S3_REGION_NAME:
        AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
    else:
        AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
    AWS_S3_FILE_OVERWRITE = False
    # Set ACL to public-read for all media files
    AWS_DEFAULT_ACL = 'public-read'
    AWS_QUERYSTRING_AUTH = (
        False  # Don't use query string authentication for public files
    )
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }

    # Media files go to S3 with public-read access
    # Note: Must use 'Hawashmart' (capital H) to match the directory name
    DEFAULT_FILE_STORAGE = "furniture_store.storage.MediaStorage"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/"
    MEDIA_ROOT = BASE_DIR / "media"

    # Static files use WhiteNoise (works better on Heroku)
    STATIC_URL = "/static/"
    STATIC_ROOT = BASE_DIR / "staticfiles"
    STATICFILES_DIRS = [
        BASE_DIR / "static",
    ]
    # Use Django's default storage - WhiteNoise middleware handles compression
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

    # WhiteNoise configuration for better static file serving
    WHITENOISE_USE_FINDERS = True  # Allow WhiteNoise to find files in STATICFILES_DIRS
    WHITENOISE_AUTOREFRESH = True  # Auto-refresh in development
else:
    # Local Static and Media files configuration
    STATIC_URL = "/static/"
    STATIC_ROOT = BASE_DIR / "staticfiles"
    STATICFILES_DIRS = [
        BASE_DIR / "static",
    ]
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"
    # Use Django's default storage - WhiteNoise middleware handles compression
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

    # WhiteNoise configuration for better static file serving
    WHITENOISE_USE_FINDERS = True  # Allow WhiteNoise to find files in STATICFILES_DIRS
    WHITENOISE_AUTOREFRESH = True  # Auto-refresh in development


# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "accounts.User"

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Email Configuration
EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@furniturestore.com")

# Site URL - Use Heroku URL in production
SITE_URL = config("SITE_URL", default="http://localhost:8000")

# Stripe Configuration
STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY", default="")
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")

# Login URLs
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Session Configuration
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True

# Security settings for production (Heroku)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
